version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-volumes2:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    volumes:
      - .:/test-docker
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  db-volumes2:
